Repository andela/mazus-ah-frontend, pull requests merged in 2019-09, with the labels that each got.

#14 #167165017: Implements Signup and Login Page
  .eslintrc
  babel.config.js
  config/webpack.config.js
  config/webpack.dev.js
  jest.config.js
  jsconfig.json
  package-lock.json
  package.json
  src/__mocks__/axios.js
  src/app.js
  src/components/common/auth/auth.scss
  src/components/common/auth/buttons.js
  src/components/common/auth/leftDiv.js
  src/components/common/auth/leftDivText.js
  src/components/common/form/InputField.js
  src/components/common/form/InputField.spec.js
  src/components/common/form/__snapshots__/InputField.spec.js.snap
  src/components/views/auth/signIn/SignIn.spec.js
  src/components/views/auth/signIn/Signin.js
  src/components/views/auth/signIn/__snapshots__/SignIn.spec.js.snap
  src/components/views/auth/signUp/SignUp.js
  src/components/views/auth/signUp/SignUp.spec.js
  src/components/views/auth/signUp/__snapshots__/SignUp.spec.js.snap
  src/components/views/notFound/NotFound.js
  src/components/views/notFound/NotFound.spec.js
  src/components/views/welcome/Welcome.js
  src/components/views/welcome/Welcome.spec.js
  src/index.js
  src/redux/actions/authAction.spec.js
  src/redux/actions/authActions.js
  src/redux/actions/types/authType.js
  src/redux/reducers/__tests__/articleReducer.spec.js
  src/redux/reducers/__tests__/authReducer.spec.js
  src/redux/reducers/articleReducer.test.js
  src/redux/reducers/authReducer.js
  src/redux/reducers/index.js
  utils/API.js
  utils/setAuthToken.js
Labels: work in progress

#21 #168369630: Implements PO Feedback On Signup
  src/components/common/auth/auth.scss
  src/components/views/auth/signUp/SignUp.js
  utils/validatePassword.js
Labels: ready to be merged

#22 feat(logout): User should be able to logout
  src/components/common/header/AuthenticatedHeader.js
  src/components/common/header/Header.spec.js
  src/redux/actions/authAction.spec.js
  src/redux/actions/authActions.js
  src/redux/actions/types/authType.js
  src/redux/reducers/__tests__/authReducer.spec.js
  src/redux/reducers/authReducer.js
  utils/API.js
Labels: ready to be merged

#20 #168359288 Fix landing page responsiveness
  src/components/common/landingPage/card/cards.scss
  src/components/common/landingPage/categories/Categories.js
  src/components/common/landingPage/categories/categories.scss
  src/components/common/landingPage/tagsDiv/tagsDiv.scss
  src/components/common/landingPage/trending/Trending.js
  src/components/common/landingPage/trending/trending.scss
  src/components/common/landingPage/trending/trending.spec.js
  src/components/views/landingPage/landingPage.scss
  src/redux/actions/articleActions.js
  src/redux/actions/articleActions.spec.js
  src/redux/actions/types/articleType.js
  src/redux/reducers/__tests__/articleReducer.spec.js
  src/redux/reducers/articleReducer.js
Labels: ready to merge

#23 #167165024 User Should Be Able To Comment On An Article
  jsconfig.json
  package.json
  src/components/common/comments/ArticleComment.js
  src/components/common/comments/ArticleComment.spec.js
  src/components/common/comments/ArticleCommentForm.js
  src/components/common/comments/ArticleCommentList.js
  src/components/common/comments/articleComment.scss
  src/components/common/form/__snapshots__/textArea.spec.js.snap
  src/components/common/form/textArea.js
  src/components/common/form/textArea.spec.js
  src/components/common/hoc/ContainerWrapper.spec.js
  src/components/views/article/Article.js
  src/components/views/article/Article.spec.js
  src/components/views/article/article.scss
  src/redux/actions/articleActions.js
  src/redux/actions/articleActions.spec.js
  src/redux/actions/socialActions.js
  src/redux/actions/socialActions.spec.js
  src/redux/actions/types/articleType.js
  src/redux/reducers/__tests__/__snapshots__/articleReducer.spec.js.snap
  src/redux/reducers/__tests__/articleReducer.spec.js
  src/redux/reducers/articleReducer.js
Labels: ready to be merged
